package com.salestracker.expense;

import com.fasterxml.jackson.databind.JsonNode;
import com.salestracker.AbstractIntegrationTest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;

class ExpenseIntegrationTest extends AbstractIntegrationTest {

    private Tenant tenant;
    private long facebook;
    private long daraz;
    private long customer;
    private long rice; // cost 100

    @BeforeEach
    void setUp() throws Exception {
        tenant = registerTenant();
        for (JsonNode p : get(tenant, "/api/platforms", 200)) {
            if (p.get("name").asText().equals("Facebook Page")) facebook = p.get("id").asLong();
            if (p.get("name").asText().equals("Daraz")) daraz = p.get("id").asLong();
        }
        customer = post(tenant, "/api/customers", "{\"name\":\"Buyer\"}", 201).get("id").asLong();
        rice = post(tenant, "/api/products", "{\"name\":\"Rice\",\"costPrice\":100,\"sellingPrice\":150}", 201).get("id").asLong();
    }

    // ---- helpers ----

    private void setCommission(long platformId, String name, String pct) throws Exception {
        put(tenant, "/api/platforms/" + platformId, "{\"name\":\"%s\",\"commissionPct\":%s}".formatted(name, pct), 200);
    }

    /** One line, quantity qty at soldPrice each. */
    private JsonNode order(long platformId, String status, String orderedAt, int qty, String soldPrice) throws Exception {
        return post(tenant, "/api/orders", orderBody(platformId, status, orderedAt, qty, soldPrice), 201);
    }

    private String orderBody(long platformId, String status, String orderedAt, int qty, String soldPrice) {
        return """
                {"platformId":%d,"customerId":%d,"status":"%s","orderedAt":"%s",
                 "items":[{"productId":%d,"quantity":%d,"soldPrice":%s}]}
                """.formatted(platformId, customer, status, orderedAt, rice, qty, soldPrice);
    }

    private JsonNode expense(String type, String amount, String date, String description, Long orderId) throws Exception {
        return post(tenant, "/api/expenses", """
                {"type":"%s","amount":%s,"expenseDate":"%s","description":%s,"orderId":%s}
                """.formatted(type, amount, date, description == null ? "null" : "\"" + description + "\"",
                orderId == null ? "null" : orderId), 201);
    }

    private JsonNode orderExpenses(long orderId) throws Exception {
        return get(tenant, "/api/orders/" + orderId, 200).get("expenses");
    }

    private static void assertMoney(String expected, JsonNode actual) {
        assertEquals(0, new BigDecimal(expected).compareTo(actual.decimalValue()), "expected " + expected + " but was " + actual);
    }

    // ---- manual expenses ----

    @Test
    void manualExpenseLifecycle() throws Exception {
        JsonNode created = expense("DELIVERY", "60", "2026-09-10", "Pathao courier", null);
        assertEquals("DELIVERY", created.get("type").asText());
        assertMoney("60", created.get("amount"));
        assertEquals("2026-09-10", created.get("expenseDate").asText());
        assertEquals("Pathao courier", created.get("description").asText());
        assertFalse(created.get("autoGenerated").asBoolean());
        assertTrue(created.get("orderId").isNull());
        long id = created.get("id").asLong();

        JsonNode updated = put(tenant, "/api/expenses/" + id,
                "{\"type\":\"PACKAGING\",\"amount\":25.50,\"expenseDate\":\"2026-09-11\",\"description\":\"\"}", 200);
        assertEquals("PACKAGING", updated.get("type").asText());
        assertMoney("25.50", updated.get("amount"));
        assertTrue(updated.get("description").isNull(), "blank description is stored as null");

        assertEquals(1, get(tenant, "/api/expenses", 200).get("totalElements").asInt());
        delete(tenant, "/api/expenses/" + id, 204);
        assertEquals(0, get(tenant, "/api/expenses", 200).get("totalElements").asInt());
        delete(tenant, "/api/expenses/" + id, 404);
        put(tenant, "/api/expenses/" + id, "{\"type\":\"MISC\",\"amount\":1,\"expenseDate\":\"2026-09-11\"}", 404);
    }

    @Test
    void invalidExpensesAreRejected() throws Exception {
        String ok = "\"expenseDate\":\"2026-09-10\"";
        post(tenant, "/api/expenses", "{\"amount\":10," + ok + "}", 400);                                   // no type
        post(tenant, "/api/expenses", "{\"type\":\"DELIVERY\"," + ok + "}", 400);                           // no amount
        post(tenant, "/api/expenses", "{\"type\":\"DELIVERY\",\"amount\":0," + ok + "}", 400);              // zero
        post(tenant, "/api/expenses", "{\"type\":\"DELIVERY\",\"amount\":-5," + ok + "}", 400);             // negative
        post(tenant, "/api/expenses", "{\"type\":\"DELIVERY\",\"amount\":1.234," + ok + "}", 400);          // 3 decimals
        post(tenant, "/api/expenses", "{\"type\":\"DELIVERY\",\"amount\":10}", 400);                        // no date
        post(tenant, "/api/expenses", "{\"type\":\"TELEPORT\",\"amount\":10," + ok + "}", 400);             // unknown type
        post(tenant, "/api/expenses", "{\"type\":\"DELIVERY\",\"amount\":10,\"expenseDate\":\"yesterday\"}", 400);
        post(tenant, "/api/expenses", "{\"type\":\"DELIVERY\",\"amount\":10," + ok + ",\"orderId\":999999}", 400);
        assertEquals(0, get(tenant, "/api/expenses", 200).get("totalElements").asInt(), "nothing half-created");
    }

    @Test
    void listFiltersAndSummary() throws Exception {
        long o = order(facebook, "PAID", "2026-09-10T10:00", 1, "150").get("id").asLong();
        expense("DELIVERY", "60", "2026-09-10", "courier", o);
        expense("PACKAGING", "20", "2026-09-11", null, o);
        expense("ADS", "500", "2026-08-20", "boost", null);
        expense("MISC", "5", "2026-09-30", null, null);

        JsonNode all = get(tenant, "/api/expenses", 200);
        assertEquals(4, all.get("totalElements").asInt());
        assertEquals("MISC", all.at("/content/0/type").asText(), "newest first");
        assertEquals("ADS", all.at("/content/3/type").asText());

        assertEquals(1, get(tenant, "/api/expenses?type=DELIVERY", 200).get("totalElements").asInt());
        assertEquals(3, get(tenant, "/api/expenses?from=2026-09-01&to=2026-09-30", 200).get("totalElements").asInt());
        assertEquals(2, get(tenant, "/api/expenses?orderId=" + o, 200).get("totalElements").asInt());
        JsonNode linked = get(tenant, "/api/expenses?type=DELIVERY", 200).at("/content/0");
        assertEquals(o, linked.get("orderId").asLong());
        assertEquals("Facebook Page", linked.get("platformName").asText());
        assertEquals(1, get(tenant, "/api/expenses?type=DELIVERY&from=2026-09-01&to=2026-09-30&orderId=" + o, 200).get("totalElements").asInt());
        assertEquals(0, get(tenant, "/api/expenses?type=ADS&from=2026-09-01", 200).get("totalElements").asInt());

        JsonNode september = get(tenant, "/api/expenses/summary?from=2026-09-01&to=2026-09-30", 200);
        assertMoney("85", september.get("total"));
        assertEquals(3, september.get("count").asInt());
        assertEquals(3, september.get("byType").size());
        assertEquals("DELIVERY", september.at("/byType/0/type").asText(), "largest first");
        assertMoney("60", september.at("/byType/0/total"));

        JsonNode allTime = get(tenant, "/api/expenses/summary", 200);
        assertMoney("585", allTime.get("total"));
        assertEquals("ADS", allTime.at("/byType/0/type").asText());

        get(tenant, "/api/expenses?from=2026-09-30&to=2026-09-01", 400);
        get(tenant, "/api/expenses?type=NOPE", 400);
    }

    // ---- automatic platform commission ----

    @Test
    void commissionIsCalculatedOnPlatformOrdersAndOnlyThose() throws Exception {
        setCommission(daraz, "Daraz", "10");

        JsonNode darazOrder = order(daraz, "PAID", "2026-09-05T10:00", 2, "150"); // revenue 300
        assertMoney("10", darazOrder.get("commissionPct"));
        JsonNode lines = darazOrder.get("expenses");
        assertEquals(1, lines.size());
        assertEquals("PLATFORM_COMMISSION", lines.get(0).get("type").asText());
        assertMoney("30", lines.get(0).get("amount"));
        assertTrue(lines.get(0).get("autoGenerated").asBoolean());
        assertEquals("Daraz commission (10%)", lines.get(0).get("description").asText());

        JsonNode listed = get(tenant, "/api/expenses?orderId=" + darazOrder.get("id").asLong(), 200).at("/content/0");
        assertEquals("2026-09-05", listed.get("expenseDate").asText(), "commission is dated with the sale");
        assertEquals("Daraz", listed.get("platformName").asText());
        assertTrue(listed.get("autoGenerated").asBoolean());

        JsonNode facebookOrder = order(facebook, "PAID", "2026-09-05T11:00", 2, "150");
        assertEquals(0, facebookOrder.get("expenses").size(), "0% platform: no commission expense");
    }

    @Test
    void commissionFollowsTheOrderStatus() throws Exception {
        setCommission(daraz, "Daraz", "10");
        long id = order(daraz, "PAID", "2026-09-05T10:00", 2, "150").get("id").asLong();

        assertEquals(1, patch(tenant, "/api/orders/" + id + "/status", "{\"status\":\"PENDING\"}", 200).get("expenses").size(),
                "a pending sale still accrues commission");
        assertEquals(0, patch(tenant, "/api/orders/" + id + "/status", "{\"status\":\"RETURNED\"}", 200).get("expenses").size(),
                "a returned order gets its commission back");
        JsonNode paidAgain = patch(tenant, "/api/orders/" + id + "/status", "{\"status\":\"PAID\"}", 200);
        assertEquals(1, paidAgain.get("expenses").size());
        assertMoney("30", paidAgain.at("/expenses/0/amount"));
        assertEquals(0, patch(tenant, "/api/orders/" + id + "/status", "{\"status\":\"CANCELLED\"}", 200).get("expenses").size());
        assertEquals(0, get(tenant, "/api/expenses", 200).get("totalElements").asInt(), "no orphan rows left behind");
    }

    @Test
    void editingAnOrderRecalculatesItsCommissionWithoutDuplicating() throws Exception {
        setCommission(daraz, "Daraz", "10");
        long id = order(daraz, "PAID", "2026-09-05T10:00", 2, "150").get("id").asLong();

        JsonNode edited = put(tenant, "/api/orders/" + id, orderBody(daraz, "PAID", "2026-09-07T09:00", 5, "100"), 200);
        assertEquals(1, edited.get("expenses").size(), "updated in place, not duplicated");
        assertMoney("50", edited.at("/expenses/0/amount")); // revenue 500 x 10%
        JsonNode row = get(tenant, "/api/expenses?orderId=" + id, 200).at("/content/0");
        assertEquals("2026-09-07", row.get("expenseDate").asText(), "follows the order date");

        // moving the sale to a 0% platform removes it; moving back re-applies the platform's current rate
        JsonNode toFacebook = put(tenant, "/api/orders/" + id, orderBody(facebook, "PAID", "2026-09-07T09:00", 5, "100"), 200);
        assertEquals(0, toFacebook.get("expenses").size());
        assertMoney("0", toFacebook.get("commissionPct"));
        JsonNode backToDaraz = put(tenant, "/api/orders/" + id, orderBody(daraz, "PAID", "2026-09-07T09:00", 5, "100"), 200);
        assertMoney("50", backToDaraz.at("/expenses/0/amount"));
    }

    @Test
    void theRateIsSnapshottedSoChangingItLaterDoesNotRewriteHistory() throws Exception {
        setCommission(daraz, "Daraz", "10");
        long old = order(daraz, "PAID", "2026-09-05T10:00", 2, "150").get("id").asLong(); // 30.00

        setCommission(daraz, "Daraz", "20");

        JsonNode fresh = order(daraz, "PAID", "2026-09-06T10:00", 2, "150");
        assertMoney("20", fresh.get("commissionPct"));
        assertMoney("60", fresh.at("/expenses/0/amount"));

        JsonNode oldStill = get(tenant, "/api/orders/" + old, 200);
        assertMoney("10", oldStill.get("commissionPct"));
        assertMoney("30", oldStill.at("/expenses/0/amount"));

        // editing or re-statusing the old order (same platform) keeps its original rate
        JsonNode edited = put(tenant, "/api/orders/" + old, orderBody(daraz, "PAID", "2026-09-05T10:00", 4, "150"), 200);
        assertMoney("10", edited.get("commissionPct"));
        assertMoney("60", edited.at("/expenses/0/amount")); // 600 x 10%, not x 20%
        patch(tenant, "/api/orders/" + old + "/status", "{\"status\":\"RETURNED\"}", 200);
        assertMoney("60", patch(tenant, "/api/orders/" + old + "/status", "{\"status\":\"PAID\"}", 200).at("/expenses/0/amount"));
    }

    @Test
    void commissionRoundsHalfUpToTwoDecimalsAndSkipsZero() throws Exception {
        setCommission(daraz, "Daraz", "4.5");
        assertMoney("4.50", order(daraz, "PAID", "2026-09-05T10:00", 1, "100.01").at("/expenses/0/amount")); // 4.50045

        setCommission(daraz, "Daraz", "0.05");
        assertMoney("0.01", order(daraz, "PAID", "2026-09-05T10:00", 1, "10").at("/expenses/0/amount")); // 0.005 -> 0.01

        setCommission(daraz, "Daraz", "10");
        assertEquals(0, order(daraz, "PAID", "2026-09-05T10:00", 1, "0").get("expenses").size(), "a free giveaway earns no commission");
    }

    @Test
    void automaticCommissionRowsAreReadOnly() throws Exception {
        setCommission(daraz, "Daraz", "10");
        long orderId = order(daraz, "PAID", "2026-09-05T10:00", 2, "150").get("id").asLong();
        long autoId = orderExpenses(orderId).get(0).get("id").asLong();

        put(tenant, "/api/expenses/" + autoId,
                "{\"type\":\"PLATFORM_COMMISSION\",\"amount\":1,\"expenseDate\":\"2026-09-05\"}", 409);
        delete(tenant, "/api/expenses/" + autoId, 409);
        assertMoney("30", orderExpenses(orderId).get(0).get("amount"));
    }

    @Test
    void manualExpensesOnAnOrderSurviveStatusChangesAndEditsButDieWithTheOrder() throws Exception {
        setCommission(daraz, "Daraz", "10");
        long orderId = order(daraz, "PAID", "2026-09-05T10:00", 2, "150").get("id").asLong();
        expense("DELIVERY", "60", "2026-09-05", "courier", orderId);
        assertEquals(2, orderExpenses(orderId).size(), "delivery + commission");

        // a returned order still cost the delivery fee, but the platform refunds its commission
        JsonNode returned = patch(tenant, "/api/orders/" + orderId + "/status", "{\"status\":\"RETURNED\"}", 200);
        assertEquals(1, returned.get("expenses").size());
        assertEquals("DELIVERY", returned.at("/expenses/0/type").asText());
        assertMoney("60", returned.at("/expenses/0/amount"));

        put(tenant, "/api/orders/" + orderId, orderBody(daraz, "PAID", "2026-09-05T10:00", 3, "150"), 200);
        assertEquals(2, orderExpenses(orderId).size());

        delete(tenant, "/api/orders/" + orderId, 204);
        assertEquals(0, get(tenant, "/api/expenses", 200).get("totalElements").asInt(), "expenses go with their order");
    }

    // ---- isolation ----

    @Test
    void anotherBusinessSeesNoneOfItAndCannotTouchIt() throws Exception {
        setCommission(daraz, "Daraz", "10");
        long orderId = order(daraz, "PAID", "2026-09-05T10:00", 2, "150").get("id").asLong();
        long manual = expense("DELIVERY", "60", "2026-09-05", null, orderId).get("id").asLong();

        Tenant other = registerTenant();
        assertEquals(0, get(other, "/api/expenses", 200).get("totalElements").asInt());
        assertMoney("0", get(other, "/api/expenses/summary", 200).get("total"));
        assertEquals(0, get(other, "/api/expenses?orderId=" + orderId, 200).get("totalElements").asInt());

        put(other, "/api/expenses/" + manual, "{\"type\":\"MISC\",\"amount\":1,\"expenseDate\":\"2026-09-05\"}", 404);
        delete(other, "/api/expenses/" + manual, 404);
        post(other, "/api/expenses", "{\"type\":\"MISC\",\"amount\":1,\"expenseDate\":\"2026-09-05\",\"orderId\":" + orderId + "}", 400);
        get(other, "/api/orders/" + orderId, 404);

        assertEquals(2, orderExpenses(orderId).size(), "untouched");
    }
}
