import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import api, { errorMessage } from '../api/client'
import { useAuth } from '../auth/AuthContext'
import AsyncPicker from '../components/AsyncPicker'
import { EXPENSE_LABEL, EXPENSE_TYPES, STATUSES, STATUS_LABEL, money, toLocalInput } from '../utils/format'

const searchProducts = (q) => api.get('/products', { params: { q, size: 10 } }).then((r) => r.data.content)
const searchCustomers = (q) => api.get('/customers', { params: { q, size: 10 } }).then((r) => r.data.content)

let lineKey = 0
const newLine = (product, extra = {}) => ({
  key: ++lineKey,
  productId: product.id,
  name: product.name,
  cost: Number(product.costPrice),
  quantity: 1,
  soldPrice: product.sellingPrice ?? '',
  ...extra,
})

let expenseKey = 0
const newExpense = (type = 'DELIVERY') => ({ key: ++expenseKey, type, amount: '', description: '' })

export default function OrderForm() {
  const { user } = useAuth()
  const isOwner = user?.role === 'OWNER'
  const { id } = useParams()
  const editing = Boolean(id)
  const navigate = useNavigate()

  const [platforms, setPlatforms] = useState([])
  const [platformId, setPlatformId] = useState('')
  const [customer, setCustomer] = useState(null) // picked existing customer
  const [isNewCustomer, setIsNewCustomer] = useState(false)
  const [nc, setNc] = useState({ name: '', phone: '', address: '' })
  const [status, setStatus] = useState('PAID')
  const [orderedAt, setOrderedAt] = useState(toLocalInput())
  const [notes, setNotes] = useState('')
  const [deliveryCharge, setDeliveryCharge] = useState('')
  const [lines, setLines] = useState([])
  const [original, setOriginal] = useState(null) // { platformId, rate, expenses } of the order being edited
  const [newExpenses, setNewExpenses] = useState([]) // expense rows typed here, saved with the order
  const [removedExpenseIds, setRemovedExpenseIds] = useState([]) // existing ones to delete on save
  const [savedId, setSavedId] = useState(null) // set once a new sale is stored, so a retry updates instead of duplicating
  const [loading, setLoading] = useState(editing)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)

  useEffect(() => {
    api.get('/platforms').then((res) => {
      setPlatforms(res.data)
      if (!editing && res.data.length) setPlatformId(String(res.data[0].id))
    }).catch(() => {})
  }, [editing])

  useEffect(() => {
    if (!editing) return
    api.get(`/orders/${id}`).then(({ data: o }) => {
      setPlatformId(String(o.platformId))
      setOriginal({ platformId: String(o.platformId), rate: Number(o.commissionPct), expenses: o.expenses })
      setCustomer({ id: o.customerId, name: o.customerName, phone: o.customerPhone })
      setStatus(o.status)
      setOrderedAt(o.orderedAt.slice(0, 16))
      setNotes(o.notes ?? '')
      setDeliveryCharge(Number(o.deliveryCharge) > 0 ? o.deliveryCharge : '')
      setLines(o.items.map((i) => newLine(
        { id: i.productId, name: i.productName, costPrice: i.costPrice },
        { quantity: i.quantity, soldPrice: i.soldPrice },
      )))
    }).catch((err) => setError(errorMessage(err))).finally(() => setLoading(false))
  }, [editing, id])

  const addProduct = (product) => {
    if (lines.some((l) => l.productId === product.id)) {
      setError(`"${product.name}" is already on this order; change its quantity instead.`)
      return
    }
    setError('')
    setLines([...lines, newLine(product)])
  }
  const updateLine = (key, patch) => setLines(lines.map((l) => (l.key === key ? { ...l, ...patch } : l)))
  const removeLine = (key) => setLines(lines.filter((l) => l.key !== key))

  const lineProfit = (l) => (Number(l.soldPrice || 0) - l.cost) * Number(l.quantity || 0)
  const revenue = lines.reduce((s, l) => s + Number(l.soldPrice || 0) * Number(l.quantity || 0), 0)
  const cost = lines.reduce((s, l) => s + l.cost * Number(l.quantity || 0), 0)
  const delivery = Number(deliveryCharge || 0)
  const profit = revenue - cost
  const margin = revenue > 0 ? Math.round((profit / revenue) * 100) : 0
  const units = lines.reduce((s, l) => s + Number(l.quantity || 0), 0)

  // The rate a sale is charged: an edited order keeps the rate it was recorded at unless its platform changes.
  const platform = platforms.find((p) => String(p.id) === platformId)
  const rate = editing && original && platformId === original.platformId ? original.rate : Number(platform?.commissionPct ?? 0)
  const accrues = status === 'PAID' || status === 'PENDING'
  const commission = accrues ? Math.round(revenue * rate) / 100 : 0
  // Existing expenses minus any marked for removal; the automatic commission is left out because the server
  // recalculates it on save, so the live estimate above stands in for it.
  const keptExpenses = (original?.expenses ?? []).filter((x) => !x.autoGenerated && !removedExpenseIds.includes(x.id))
  const autoExpenses = (original?.expenses ?? []).filter((x) => x.autoGenerated)
  const expenseTotal = keptExpenses.reduce((s, x) => s + Number(x.amount), 0)
    + newExpenses.reduce((s, x) => s + Number(x.amount || 0), 0)
    + commission
  const netProfit = profit + delivery - expenseTotal

  const addExpense = (type) => setNewExpenses([...newExpenses, newExpense(type)])
  const updateExpense = (key, patch) => setNewExpenses(newExpenses.map((x) => (x.key === key ? { ...x, ...patch } : x)))
  const dropExpense = (key) => setNewExpenses(newExpenses.filter((x) => x.key !== key))

  /** Runs after the order itself is saved; each step drops out of state once done so a retry never repeats it. */
  const saveExpenses = async (orderId) => {
    for (const expenseId of removedExpenseIds) {
      await api.delete(`/expenses/${expenseId}`)
      setRemovedExpenseIds((ids) => ids.filter((i) => i !== expenseId))
    }
    for (const x of newExpenses) {
      await api.post('/expenses', {
        type: x.type, amount: x.amount, description: x.description, orderId, expenseDate: orderedAt.slice(0, 10),
      })
      setNewExpenses((rows) => rows.filter((r) => r.key !== x.key))
    }
  }

  const submit = async (e) => {
    e.preventDefault()
    setError('')
    if (lines.length === 0) return setError('Add at least one product.')
    if (!isNewCustomer && !customer) return setError('Pick a customer or add a new one.')
    if (newExpenses.some((x) => !(Number(x.amount) > 0))) return setError('Enter an amount for every expense, or remove it.')

    const body = {
      platformId: Number(platformId),
      customerId: isNewCustomer ? null : customer.id,
      newCustomer: isNewCustomer ? nc : null,
      status,
      orderedAt,
      notes,
      deliveryCharge: deliveryCharge === '' ? 0 : deliveryCharge,
      items: lines.map((l) => ({ productId: l.productId, quantity: Number(l.quantity), soldPrice: l.soldPrice })),
    }
    setBusy(true)
    let orderId = id ?? savedId
    try {
      const { data: o } = orderId ? await api.put(`/orders/${orderId}`, body) : await api.post('/orders', body)
      orderId = o.id
      setSavedId(o.id)
      // A quick-added customer now exists; a retry must point at it rather than add them twice.
      setCustomer({ id: o.customerId, name: o.customerName, phone: o.customerPhone })
      setIsNewCustomer(false)
    } catch (err) {
      setError(errorMessage(err))
      setBusy(false)
      return
    }
    try {
      await saveExpenses(orderId)
      navigate('/orders')
    } catch (err) {
      // The order is in; pressing save again updates it (savedId) and retries only the expenses still listed.
      setError(`The sale was saved, but an expense wasn't: ${errorMessage(err)}`)
      setBusy(false)
    }
  }

  if (loading) return <p className="center-note">Loading…</p>

  return (
    <section className="order-form">
      <div className="page-head">
        <div>
          <p className="eyebrow">{editing ? 'Orders' : 'Record a sale'}</p>
          <h1>{editing ? `Edit order #${id}` : 'New sale'}</h1>
        </div>
        <Link className="btn secondary" to="/orders">← Back to orders</Link>
      </div>

      <form className="of-grid" onSubmit={submit}>
        <div className="of-main">
          <div className="of-card">
            <h2 className="of-title"><span className="of-step">1</span>Sale details</h2>
            <div className="row">
              <label>
                Platform
                <select required value={platformId} onChange={(e) => setPlatformId(e.target.value)}>
                  {platforms.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}
                </select>
              </label>
              <label>
                Date &amp; time
                <input required type="datetime-local" value={orderedAt} onChange={(e) => setOrderedAt(e.target.value)} />
              </label>
            </div>
            <div className="of-field">
              <span className="of-label" id="status-label">Status</span>
              <div className="status-pills" role="radiogroup" aria-labelledby="status-label">
                {STATUSES.map((s) => (
                  <button key={s} type="button" role="radio" aria-checked={status === s}
                          className={`status-pill ${s}${status === s ? ' on' : ''}`} onClick={() => setStatus(s)}>
                    <span className="dot" />{STATUS_LABEL[s]}
                  </button>
                ))}
              </div>
            </div>
          </div>

          <div className="of-card">
            <div className="of-card-head">
              <h2 className="of-title"><span className="of-step">2</span>Customer</h2>
              {isNewCustomer
                ? <button type="button" className="link" onClick={() => setIsNewCustomer(false)}>Pick an existing customer</button>
                : <button type="button" className="link" onClick={() => setIsNewCustomer(true)}>+ New customer</button>}
            </div>
            {!isNewCustomer ? (
              customer ? (
                <div className="chosen-card">
                  <span className="avatar">{customer.name?.trim()?.[0]?.toUpperCase() ?? '?'}</span>
                  <div className="chosen-text">
                    <b>{customer.name}</b>
                    {customer.phone && <span className="muted">{customer.phone}</span>}
                  </div>
                  <button type="button" className="btn secondary small" onClick={() => setCustomer(null)}>Change</button>
                </div>
              ) : (
                <AsyncPicker search={searchCustomers} placeholder="Search customer by name or phone…"
                             label={(c) => `${c.name}${c.phone ? ' · ' + c.phone : ''}`} onPick={setCustomer} />
              )
            ) : (
              <>
                <div className="row">
                  <label>Name<input required value={nc.name} onChange={(e) => setNc({ ...nc, name: e.target.value })} /></label>
                  <label>Phone<input value={nc.phone} onChange={(e) => setNc({ ...nc, phone: e.target.value })} /></label>
                </div>
                <label>Address<input value={nc.address} onChange={(e) => setNc({ ...nc, address: e.target.value })} /></label>
              </>
            )}
          </div>

          <div className="of-card">
            <div className="of-card-head">
              <h2 className="of-title"><span className="of-step">3</span>Products</h2>
              {lines.length > 0 && (
                <span className="muted small-text">
                  {lines.length} {lines.length === 1 ? 'product' : 'products'} · {units} {units === 1 ? 'unit' : 'units'}
                </span>
              )}
            </div>
            <AsyncPicker search={searchProducts} placeholder="Search products by name or SKU to add…"
                         label={(p) => `${p.name}${p.sku ? ' (' + p.sku + ')' : ''} · ${money(p.sellingPrice)}`}
                         onPick={addProduct} />
            {lines.length === 0 ? (
              <div className="of-empty">
                <svg viewBox="0 0 24 24" width="28" height="28" aria-hidden="true" fill="none" stroke="currentColor"
                     strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M6 7h12l-1 13H7L6 7z" /><path d="M9 7a3 3 0 0 1 6 0" />
                </svg>
                <p>No products yet. Search above to add the first one.</p>
              </div>
            ) : (
              <div className="table-wrap">
                <table>
                  <thead>
                    <tr><th>Product</th><th className="num">Qty</th><th className="num">Sold price</th>
                        {isOwner && <><th className="num">Cost</th><th className="num">Line profit</th></>}<th /></tr>
                  </thead>
                  <tbody>
                    {lines.map((l) => (
                      <tr key={l.key}>
                        <td className="line-name">{l.name}</td>
                        <td className="num">
                          <input className="small qty" type="number" min="1" step="1" required aria-label={`Quantity of ${l.name}`}
                                 value={l.quantity} onChange={(e) => updateLine(l.key, { quantity: e.target.value })} />
                        </td>
                        <td className="num">
                          <input className="small" type="number" min="0" step="0.01" required aria-label={`Sold price of ${l.name}`}
                                 value={l.soldPrice} onChange={(e) => updateLine(l.key, { soldPrice: e.target.value })} />
                        </td>
                        {isOwner && <>
                          <td className="num muted">{money(l.cost)}</td>
                          <td className={`num ${lineProfit(l) < 0 ? 'neg' : 'pos'}`}><b>{money(lineProfit(l))}</b></td>
                        </>}
                        <td className="row-actions">
                          <button type="button" className="icon-btn" aria-label={`Remove ${l.name}`} title="Remove"
                                  onClick={() => removeLine(l.key)}>✕</button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          <div className="of-card">
            <h2 className="of-title"><span className="of-step">4</span>Delivery &amp; notes</h2>
            <label>
              Delivery charge paid by the customer
              <input type="number" min="0" step="0.01" placeholder="0" value={deliveryCharge}
                     onChange={(e) => setDeliveryCharge(e.target.value)} />
              <span className="hint">Money the customer paid for delivery on top of the products. Leave empty for free delivery.
                Record what the courier charged you as a Delivery expense; the two cancel out in net profit.</span>
            </label>
            <label>
              Notes
              <textarea rows={3} value={notes} placeholder="Order number, tracking, anything worth remembering…"
                        onChange={(e) => setNotes(e.target.value)} />
            </label>
          </div>

          {isOwner && (
            <div className="of-card">
              <div className="of-card-head">
                <h2 className="of-title"><span className="of-step">5</span>Expenses <span className="muted of-optional">optional</span></h2>
              </div>
              <p className="hint of-lead">What this sale cost you beyond the product: courier, packaging, a boost… They come off the net profit.</p>

              {(keptExpenses.length > 0 || autoExpenses.length > 0) && (
                <ul className="expense-list">
                  {autoExpenses.map((x) => (
                    <li key={x.id}>
                      <span>{EXPENSE_LABEL[x.type]} <span className="badge auto">Auto</span>{x.description ? ` · ${x.description}` : ''}</span>
                      <b>{money(x.amount)}</b>
                    </li>
                  ))}
                  {keptExpenses.map((x) => (
                    <li key={x.id}>
                      <span>{EXPENSE_LABEL[x.type]}{x.description ? ` · ${x.description}` : ''}</span>
                      <span className="expense-end">
                        <b>{money(x.amount)}</b>
                        <button type="button" className="icon-btn" aria-label={`Remove ${EXPENSE_LABEL[x.type]} expense`} title="Remove"
                                onClick={() => setRemovedExpenseIds([...removedExpenseIds, x.id])}>✕</button>
                      </span>
                    </li>
                  ))}
                </ul>
              )}

              {newExpenses.map((x) => (
                <div className="expense-row" key={x.key}>
                  <select aria-label="Expense type" value={x.type} onChange={(e) => updateExpense(x.key, { type: e.target.value })}>
                    {EXPENSE_TYPES.map((t) => <option key={t} value={t}>{EXPENSE_LABEL[t]}</option>)}
                  </select>
                  <input type="number" min="0.01" step="0.01" placeholder="Amount" aria-label="Expense amount" required
                         value={x.amount} onChange={(e) => updateExpense(x.key, { amount: e.target.value })} />
                  <input placeholder="Note (optional)" aria-label="Expense note" maxLength={255}
                         value={x.description} onChange={(e) => updateExpense(x.key, { description: e.target.value })} />
                  <button type="button" className="icon-btn" aria-label="Remove this expense" title="Remove"
                          onClick={() => dropExpense(x.key)}>✕</button>
                </div>
              ))}

              <div className="quick-add">
                {['DELIVERY', 'PACKAGING', 'ADS', 'MISC'].map((t) => (
                  <button key={t} type="button" className="chip" onClick={() => addExpense(t)}>+ {EXPENSE_LABEL[t]}</button>
                ))}
              </div>
            </div>
          )}
        </div>

        <aside className="of-side">
          <div className="of-summary">
            <h2 className="of-title">Summary</h2>
            <dl className="sum-rows">
              <div><dt>Revenue</dt><dd>{money(revenue)}</dd></div>
              {isOwner && <div><dt>Cost</dt><dd>{money(cost)}</dd></div>}
              {delivery > 0 && <div className="sum-strong"><dt>Customer pays</dt><dd>{money(revenue + delivery)}</dd></div>}
            </dl>
            {isOwner && (
              <>
                <dl className="sum-rows">
                  <div><dt>Gross profit</dt><dd className={profit < 0 ? 'neg' : ''}>{money(profit)}</dd></div>
                  {delivery > 0 && <div><dt>+ Delivery charge</dt><dd>{money(delivery)}</dd></div>}
                  <div><dt>− Expenses</dt><dd>{money(expenseTotal)}</dd></div>
                </dl>
                <div className={`profit-box ${netProfit < 0 ? 'neg' : 'pos'}`}>
                  <span>Net profit</span>
                  <b>{money(netProfit)}</b>
                  {revenue > 0 && <small>{Math.round((netProfit / revenue) * 100)}% of revenue · gross margin {margin}%</small>}
                </div>
              </>
            )}
            {isOwner && rate > 0 && (
              <p className="hint">
                {platform?.name} commission {rate}%
                {accrues ? <> ≈ <b>{money(commission)}</b> will be added automatically as an expense.</> : ' is not charged while an order is returned or cancelled.'}
              </p>
            )}
            {error && <p className="error" role="alert">{error}</p>}
            <button className="btn block" disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Record sale'}</button>
            <Link className="btn secondary block" to="/orders">Cancel</Link>
          </div>
        </aside>
      </form>
    </section>
  )
}
