package com.salestracker.expense;

import jakarta.validation.constraints.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

public final class ExpenseDtos {
    private ExpenseDtos() {}

    public record ExpenseRequest(
            @NotNull ExpenseType type,
            @NotNull @DecimalMin("0.01") @Digits(integer = 10, fraction = 2) BigDecimal amount,
            @NotNull LocalDate expenseDate,
            @Size(max = 255) String description,
            /** Optional: the order this expense belongs to. */
            Long orderId) {}

    public record ExpenseResponse(Long id, ExpenseType type, BigDecimal amount, LocalDate expenseDate,
                                  String description, Long orderId, String platformName, boolean autoGenerated) {}

    /** The compact form shown inside an order. */
    public record ExpenseLine(Long id, ExpenseType type, BigDecimal amount, String description, boolean autoGenerated) {}

    public record TypeTotal(ExpenseType type, long count, BigDecimal total) {}

    public record ExpenseSummary(BigDecimal total, long count, List<TypeTotal> byType) {}
}
