package com.salestracker.expense;

import com.salestracker.auth.ApiException;
import com.salestracker.common.DateRange;
import com.salestracker.common.PageResponse;
import com.salestracker.common.Search;
import com.salestracker.expense.ExpenseDtos.*;
import com.salestracker.order.OrderItem;
import com.salestracker.order.OrderStatus;
import com.salestracker.order.SaleOrder;
import com.salestracker.order.SaleOrderRepository;
import com.salestracker.platform.Platform;
import com.salestracker.platform.PlatformRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;
import java.util.function.Function;
import java.util.stream.Collectors;

@Service
@Transactional
public class ExpenseService {
    private static final BigDecimal HUNDRED = BigDecimal.valueOf(100);
    private static final String AUTO_MESSAGE =
            "This commission is calculated automatically. Change the platform's commission rate or the order instead.";

    private final ExpenseRepository expenses;
    private final SaleOrderRepository orders;
    private final PlatformRepository platforms;

    public ExpenseService(ExpenseRepository expenses, SaleOrderRepository orders, PlatformRepository platforms) {
        this.expenses = expenses;
        this.orders = orders;
        this.platforms = platforms;
    }

    // ---- user-facing CRUD ----

    @Transactional(readOnly = true)
    public PageResponse<ExpenseResponse> list(Long tenantId, ExpenseType type, Long orderId, DateRange range,
                                              int page, int size) {
        Collection<ExpenseType> types = type == null ? List.of(ExpenseType.values()) : List.of(type);
        Pageable newestFirst = PageRequest.of(Math.max(page, 0), Math.min(Math.max(size, 1), 100),
                Sort.by(Sort.Order.desc("expenseDate"), Sort.Order.desc("id")));
        Page<Expense> result = expenses.search(tenantId, types, orderId == null ? 0L : orderId,
                range.from().toLocalDate(), range.toExclusive().toLocalDate(), newestFirst);
        return new PageResponse<>(responses(result.getContent()), result.getNumber(),
                result.getTotalPages(), result.getTotalElements());
    }

    @Transactional(readOnly = true)
    public ExpenseSummary summary(Long tenantId, DateRange range) {
        List<TypeTotal> byType = expenses.totalsByType(tenantId, range.from().toLocalDate(), range.toExclusive().toLocalDate())
                .stream().map(t -> new TypeTotal(t.type(), t.count(), t.total()))
                .sorted(Comparator.comparing(TypeTotal::total).reversed()).toList();
        return new ExpenseSummary(
                byType.stream().map(TypeTotal::total).reduce(BigDecimal.ZERO, BigDecimal::add),
                byType.stream().mapToLong(TypeTotal::count).sum(), byType);
    }

    public ExpenseResponse create(Long tenantId, ExpenseRequest req) {
        return save(new Expense(tenantId), req);
    }

    public ExpenseResponse update(Long tenantId, Long id, ExpenseRequest req) {
        return save(findManual(tenantId, id), req);
    }

    public void delete(Long tenantId, Long id) {
        expenses.delete(findManual(tenantId, id));
    }

    private Expense findManual(Long tenantId, Long id) {
        Expense e = expenses.findByIdAndTenantId(id, tenantId)
                .orElseThrow(() -> new ApiException(HttpStatus.NOT_FOUND, "Expense not found"));
        if (e.isAutoGenerated()) {
            throw new ApiException(HttpStatus.CONFLICT, AUTO_MESSAGE);
        }
        return e;
    }

    private ExpenseResponse save(Expense e, ExpenseRequest req) {
        if (req.orderId() != null && orders.findByIdAndTenantId(req.orderId(), e.getTenantId()).isEmpty()) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "Unknown order");
        }
        e.applyManual(req.orderId(), req.type(), req.amount(), req.expenseDate(), Search.blankToNull(req.description()));
        return responses(List.of(expenses.save(e))).get(0);
    }

    // ---- used by OrderService ----

    public List<ExpenseLine> linesFor(Long tenantId, Long orderId) {
        return expenses.findByTenantIdAndOrderIdOrderByIdAsc(tenantId, orderId).stream()
                .map(e -> new ExpenseLine(e.getId(), e.getType(), e.getAmount(), e.getDescription(), e.isAutoGenerated()))
                .toList();
    }

    /**
     * Keeps the automatic commission expense in step with the order (call after every create, edit or status change).
     * It exists while the order stands (PAID or PENDING) and the order's snapshotted rate is above zero; when the order
     * is returned or cancelled the platform refunds the fee, so the row goes away. Manual expenses are never touched.
     */
    public void syncCommission(SaleOrder order) {
        boolean accrues = order.getStatus() == OrderStatus.PAID || order.getStatus() == OrderStatus.PENDING;
        BigDecimal revenue = order.getItems().stream().map(OrderItem::lineRevenue).reduce(BigDecimal.ZERO, BigDecimal::add);
        BigDecimal amount = revenue.multiply(order.getCommissionPct()).divide(HUNDRED, 2, RoundingMode.HALF_UP);

        Optional<Expense> existing = expenses.findByOrderIdAndAutoGeneratedTrue(order.getId());
        if (!accrues || amount.signum() <= 0) {
            existing.ifPresent(expenses::delete);
            return;
        }
        String platform = platforms.findById(order.getPlatformId()).map(Platform::getName).orElse("Platform");
        Expense e = existing.orElseGet(() -> new Expense(order.getTenantId()));
        e.applyCommission(order.getId(), amount, order.getOrderedAt().toLocalDate(),
                "%s commission (%s%%)".formatted(platform, order.getCommissionPct().stripTrailingZeros().toPlainString()));
        expenses.save(e);
    }

    // ---- helpers ----

    private List<ExpenseResponse> responses(List<Expense> rows) {
        Map<Long, SaleOrder> orderById = orders.findAllById(
                        rows.stream().map(Expense::getOrderId).filter(Objects::nonNull).collect(Collectors.toSet()))
                .stream().collect(Collectors.toMap(SaleOrder::getId, Function.identity()));
        Map<Long, Platform> platformById = platforms.findAllById(
                        orderById.values().stream().map(SaleOrder::getPlatformId).collect(Collectors.toSet()))
                .stream().collect(Collectors.toMap(Platform::getId, Function.identity()));

        return rows.stream().map(e -> {
            SaleOrder o = e.getOrderId() == null ? null : orderById.get(e.getOrderId());
            String platform = o == null ? null : platformById.get(o.getPlatformId()).getName();
            return new ExpenseResponse(e.getId(), e.getType(), e.getAmount(), e.getExpenseDate(), e.getDescription(),
                    e.getOrderId(), platform, e.isAutoGenerated());
        }).toList();
    }
}
