package com.salestracker.expense;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.LocalDate;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

public interface ExpenseRepository extends JpaRepository<Expense, Long> {

    /** from is inclusive, to is exclusive; orderId 0 means "any order (or none)". */
    @Query("""
            select e from Expense e
            where e.tenantId = :tenantId
              and e.type in :types
              and (:orderId = 0L or e.orderId = :orderId)
              and e.expenseDate >= :from and e.expenseDate < :to
            """)
    Page<Expense> search(@Param("tenantId") Long tenantId, @Param("types") Collection<ExpenseType> types,
                         @Param("orderId") long orderId, @Param("from") LocalDate from, @Param("to") LocalDate to,
                         Pageable pageable);

    @Query("""
            select new com.salestracker.expense.ExpenseTypeTotals(e.type, count(e), sum(e.amount))
            from Expense e
            where e.tenantId = :tenantId and e.expenseDate >= :from and e.expenseDate < :to
            group by e.type
            """)
    List<ExpenseTypeTotals> totalsByType(@Param("tenantId") Long tenantId,
                                         @Param("from") LocalDate from, @Param("to") LocalDate to);

    Optional<Expense> findByIdAndTenantId(Long id, Long tenantId);

    Optional<Expense> findByOrderIdAndAutoGeneratedTrue(Long orderId);

    List<Expense> findByTenantIdAndOrderIdOrderByIdAsc(Long tenantId, Long orderId);
}
