package com.salestracker.expense;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.time.LocalDate;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

public interface ExpenseRepository extends JpaRepository<Expense, Long> {

    /** from is inclusive, to is exclusive; orderId 0 means "any order (or none)". */
    @Query("""
            select e from Expense e
            where e.tenantId = :tenantId
              and e.type in :types
              and (:orderId = 0L or e.orderId = :orderId)
              and e.expenseDate >= :from and e.expenseDate < :to
            """)
    Page<Expense> search(@Param("tenantId") Long tenantId, @Param("types") Collection<ExpenseType> types,
                         @Param("orderId") long orderId, @Param("from") LocalDate from, @Param("to") LocalDate to,
                         Pageable pageable);

    @Query("""
            select new com.salestracker.expense.ExpenseTypeTotals(e.type, count(e), sum(e.amount))
            from Expense e
            where e.tenantId = :tenantId and e.expenseDate >= :from and e.expenseDate < :to
            group by e.type
            """)
    List<ExpenseTypeTotals> totalsByType(@Param("tenantId") Long tenantId,
                                         @Param("from") LocalDate from, @Param("to") LocalDate to);

    // ---- expenses that reduce realized profit ----
    // Everything except expenses tied to a still-PENDING order: those belong to the pending (expected) figures and start
    // counting when the order is paid. Expenses tied to no order (ads, overhead) have no platform, so a platform filter
    // leaves them out. Dates are inclusive-from, exclusive-to, like the order queries.

    @Query("""
            select new com.salestracker.expense.ExpenseTypeTotals(e.type, count(e), sum(e.amount))
            from Expense e left join SaleOrder o on o.id = e.orderId
            where e.tenantId = :tenantId and e.expenseDate >= :from and e.expenseDate < :to
              and (o.id is null or o.status <> com.salestracker.order.OrderStatus.PENDING)
              and (:platformId = 0L or o.platformId = :platformId)
            group by e.type
            """)
    List<ExpenseTypeTotals> realizedByType(@Param("tenantId") Long tenantId, @Param("platformId") long platformId,
                                           @Param("from") LocalDate from, @Param("to") LocalDate to);

    @Query("""
            select new com.salestracker.expense.PlatformExpenses(o.platformId, sum(e.amount))
            from Expense e join SaleOrder o on o.id = e.orderId
            where e.tenantId = :tenantId and e.expenseDate >= :from and e.expenseDate < :to
              and o.status <> com.salestracker.order.OrderStatus.PENDING
              and (:platformId = 0L or o.platformId = :platformId)
            group by o.platformId
            """)
    List<PlatformExpenses> realizedByPlatform(@Param("tenantId") Long tenantId, @Param("platformId") long platformId,
                                              @Param("from") LocalDate from, @Param("to") LocalDate to);

    @Query("""
            select new com.salestracker.expense.DayExpenses(e.expenseDate, sum(e.amount))
            from Expense e left join SaleOrder o on o.id = e.orderId
            where e.tenantId = :tenantId and e.expenseDate >= :from and e.expenseDate < :to
              and (o.id is null or o.status <> com.salestracker.order.OrderStatus.PENDING)
              and (:platformId = 0L or o.platformId = :platformId)
            group by e.expenseDate
            order by e.expenseDate
            """)
    List<DayExpenses> realizedByDay(@Param("tenantId") Long tenantId, @Param("platformId") long platformId,
                                    @Param("from") LocalDate from, @Param("to") LocalDate to);

    Optional<Expense> findByIdAndTenantId(Long id, Long tenantId);

    Optional<Expense> findByOrderIdAndAutoGeneratedTrue(Long orderId);

    List<Expense> findByTenantIdAndOrderIdOrderByIdAsc(Long tenantId, Long orderId);
}
