package com.salestracker.expense;

import com.salestracker.tenant.TenantOwned;
import jakarta.persistence.*;

import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Table(name = "expenses")
public class Expense implements TenantOwned {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "tenant_id", nullable = false)
    private Long tenantId;

    /** The order this expense belongs to, if any. */
    @Column(name = "order_id")
    private Long orderId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ExpenseType type;

    @Column(nullable = false)
    private BigDecimal amount;

    @Column(name = "expense_date", nullable = false)
    private LocalDate expenseDate;

    private String description;

    /** True for the platform commission the app calculates for an order; those rows are read-only to users. */
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated;

    protected Expense() {}

    public Expense(Long tenantId) {
        this.tenantId = tenantId;
    }

    public void applyManual(Long orderId, ExpenseType type, BigDecimal amount, LocalDate expenseDate, String description) {
        this.orderId = orderId;
        this.type = type;
        this.amount = amount;
        this.expenseDate = expenseDate;
        this.description = description;
    }

    public void applyCommission(Long orderId, BigDecimal amount, LocalDate expenseDate, String description) {
        applyManual(orderId, ExpenseType.PLATFORM_COMMISSION, amount, expenseDate, description);
        this.autoGenerated = true;
    }

    public Long getId() { return id; }
    public Long getTenantId() { return tenantId; }
    public Long getOrderId() { return orderId; }
    public ExpenseType getType() { return type; }
    public BigDecimal getAmount() { return amount; }
    public LocalDate getExpenseDate() { return expenseDate; }
    public String getDescription() { return description; }
    public boolean isAutoGenerated() { return autoGenerated; }
}
